# Helm chart values
dashboard:
  extraArgs:
    - "--root-path=dashboard/local"
controller:
  extraArgs:
    - "--traefik-api-group=traefik.io"
    - "--traefik-api-version=traefik.io/v1alpha1"
  metrics:
    enabled: true
    service:
      annotations:
        newrelic.com/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8090"