kubeletDir: /var/snap/microk8s/common/var/lib/kubelet

storageClass:
  create: true
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  parameters:
#    server: nfs-server.default.svc.cluster.local
#    share: /
#    subDir:
#    mountPermissions: "0"
#    csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
#    csi.storage.k8s.io/provisioner-secret-name: "mount-options"
#    csi.storage.k8s.io/provisioner-secret-namespace: "default"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  mountOptions:
    - hard
    - nfsvers=4.1